C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/8,7/
      DATA (SPROP(I,-1,1),I=1,2)/24,0/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,3/
      DATA (SPROP(I,-2,1),I=1,2)/6,0/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/6,5/
      DATA (SPROP(I,-3,1),I=1,2)/-24,0/
      DATA TPRID(-3,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/-3,4/
      DATA (SPROP(I,-4,1),I=1,2)/-6,0/
      DATA TPRID(-4,1)/0/
      DATA (IFOREST(I,-5,1),I=1,2)/-4,-2/
      DATA (SPROP(I,-5,1),I=1,2)/21,0/
      DATA TPRID(-5,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/8,7/
      DATA (SPROP(I,-1,2),I=1,2)/0,-24/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/-1,4/
      DATA (SPROP(I,-2,2),I=1,2)/0,-6/
      DATA TPRID(-2,2)/0/
      DATA (IFOREST(I,-3,2),I=1,2)/6,5/
      DATA (SPROP(I,-3,2),I=1,2)/0,24/
      DATA TPRID(-3,2)/0/
      DATA (IFOREST(I,-4,2),I=1,2)/-3,3/
      DATA (SPROP(I,-4,2),I=1,2)/0,6/
      DATA TPRID(-4,2)/0/
      DATA (IFOREST(I,-5,2),I=1,2)/-2,-4/
      DATA (SPROP(I,-5,2),I=1,2)/0,21/
      DATA TPRID(-5,2)/0/
C     Number of configs
      DATA MAPCONFIG(0)/2/
